steps:
  # 1) Install swag CLI into a known path (module mode ON)
  - name: golang:1.24-alpine
    entrypoint: sh
    env:
      - GO111MODULE=on
      - GOBIN=/workspace/bin
    args:
      - -c
      - |
        apk add --no-cache git
        go install github.com/swaggo/swag/cmd/swag@latest


  # 3) Build container via buildpacks, target the cmd/api package
  - name: gcr.io/k8s-skaffold/pack
    args: [
      "build", "${_IMG}",
      "--builder", "paketobuildpacks/builder-jammy-base",
      "--publish",
      "--path", ".",
      "--env", "BP_GO_BUILD_FLAGS=-mod=readonly"
    ]


  # 4) (Optional) Deploy to Cloud Run as part of the build
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run","deploy","gpu-api",
        "--image","${_IMG}",
        "--region","us-central1",
        "--allow-unauthenticated",
        "--update-secrets","SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest",
        "--memory","256Mi","--cpu","0.5","--min-instances","0","--max-instances","3"
      ]


substitutions:
  _IMG: us-central1-docker.pkg.dev/gpuscanner/containers/gpu-api:latest

options:
  logging: CLOUD_LOGGING_ONLY