// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gpus": {
            "get": {
                "description": "Returns a JSON array of GPU offers (read-only).",
                "tags": [
                    "gpus"
                ],
                "summary": "List GPUs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider (e.g., vast, tensordock)",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive substring match",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Max total_cost_ph",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Min flops_per_dollar_ph",
                        "name": "min_flopsd",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "updated_at.desc",
                        "description": "Sort (e.g., updated_at.desc)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 200,
                        "description": "Limit (1-1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cmd_api.GPU"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Upstream error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_api.GPU": {
            "type": "object",
            "properties": {
                "cpu_arch": {
                    "type": "string"
                },
                "cpu_cores": {
                    "description": "CPU specs",
                    "type": "number"
                },
                "cpu_ghz": {
                    "type": "number"
                },
                "cpu_name": {
                    "type": "string"
                },
                "disk_bw_gbps": {
                    "type": "number"
                },
                "disk_cost_ph": {
                    "type": "number"
                },
                "disk_name": {
                    "type": "string"
                },
                "disk_space_gb": {
                    "description": "SSD",
                    "type": "number"
                },
                "download_cost_ph": {
                    "type": "number"
                },
                "download_mbps": {
                    "type": "number"
                },
                "duration_hours": {
                    "type": "number"
                },
                "flops_per_dollar_ph": {
                    "type": "number"
                },
                "gpu_cost_ph": {
                    "type": "number"
                },
                "gpu_mem_bw_gbps": {
                    "type": "number"
                },
                "id": {
                    "description": "Instance details",
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "description": "GPU details",
                    "type": "string"
                },
                "num_gpus": {
                    "type": "integer"
                },
                "ram_mb": {
                    "description": "Ram",
                    "type": "integer"
                },
                "reliability": {
                    "type": "number"
                },
                "source": {
                    "description": "e.g., \"tensordock\", \"vast\", etc.",
                    "type": "string"
                },
                "total_cost_ph": {
                    "description": "Cost",
                    "type": "number"
                },
                "total_flops": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "upload_cost_ph": {
                    "type": "number"
                },
                "upload_mbps": {
                    "description": "Internet",
                    "type": "number"
                },
                "vram_mb": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "GPU Catalog API",
	Description:      "Read-only list of GPU offers. Updated hourly.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
