name: Swagger Verify
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }
      - name: Install swag CLI
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Regenerate Swagger
        run: |
          $(go env GOPATH)/bin/swag init -g cmd/api/main.go -o ./cmd/api/docs
      - name: Fail if docs changed
        run: |
          git diff --exit-code -- docs || {
            echo "Swagger docs out of date. Run: swag init -g cmd/api/main.go -o ./docs"; exit 1;
          }
